# -*- coding: utf-8 -*-
"""endewakeru.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AGgzcOXi17YG092zDCbofdVmNUBdmJtO
"""

pip install open3d

from google.colab import drive
drive.mount('/content/drive')

import open3d as o3d
import numpy as np
import os

# --- ユーザーが設定する項目 ---

# 1. 入力する点群ファイルのパス
input_file = "/content/drive/MyDrive/熊本城外きれい1.ply"

# 2. 中心の点から残したい半径 (単位は点群の座標系に依存します)
# この値を大きくすると、より多くの点が残ります。
radius = 3.0

# 3. 保存するファイル名
output_file = "/content/drive/MyDrive/centered_point_cloud.ply"

# --------------------------


# ファイルの存在を確認
if not os.path.exists(input_file):
    print(f"エラー: 入力ファイルが見つかりません: {input_file}")
else:
    # 点群データを読み込む
    pcd = o3d.io.read_point_cloud(input_file)

    if not pcd.has_points():
        print("エラー: 点群の読み込みに失敗したか、点が含まれていません。")
    else:
        print(f"処理前の点の数: {len(pcd.points)}")

        # 1. 点群の重心（中心）を計算
        center = pcd.get_center()
        print(f"計算された中心座標: {center}")

        # 2. 各点が中心からどれだけ離れているか計算
        points = np.asarray(pcd.points)

        # NumPyを使って全点の中心からの距離を高速に計算
        distances = np.linalg.norm(points - center, axis=1)

        # 3. 指定した半径の内側にある点のインデックスを取得
        indices = np.where(distances <= radius)[0]

        # 4. 半径内の点群だけを抽出して新しい点群オブジェクトを作成
        centered_pcd = pcd.select_by_index(indices)

        print(f"半径 {radius} m 内の点の数: {len(centered_pcd.points)}")

        # 5. 結果をファイルに書き出す
        o3d.io.write_point_cloud(output_file, centered_pcd)
        print(f"処理後のファイルを {output_file} に保存しました。")

